const test=require('node:test'),assert=require('node:assert/strict');
const {parse,current}=require('../src/lyrics-format'),{LyricsController}=require('../src/lyrics-controller');
test('歌词支持多时间标签、毫秒和乱序，跳过元信息和非法秒数',()=>{const p=parse('[ar:测试]\n[00:20.50][00:02.125]你好\n[00:02.125]你好\n[00:99.1]非法\n[00:10]世界');assert.deepEqual(p.lines.map(l=>l.time),[2.125,10,20.5]);assert.equal(p.plain,'');assert.equal(current(p.lines,0),-1);assert.equal(current(p.lines,10),1);assert.equal(current(p.lines,22),2);assert.equal(current(p.lines,3),0);});
test('无时间歌词保留全文，纯音乐明确显示没有歌词',async()=>{const c=new LyricsController({resolve:async()=>({nolyric:true,lrc:{lyric:'纯音乐，请欣赏'}}),changed:()=>{}});await c.select(1);assert.equal(c.snapshot().status,'unavailable');assert.equal(c.snapshot().lines.length,0);assert.equal(parse('第一句\n第二句').plain,'第一句\n第二句');});
test('翻译按时间对齐，重复播放使用缓存，重新加载会请求接口',async()=>{let calls=0;const c=new LyricsController({resolve:async()=>{calls++;return {lrc:{lyric:'[00:03.00]Hello'},tlyric:{lyric:'[00:03.000]你好'}};},changed:()=>{}});await c.select(1);assert.equal(c.snapshot().lines[0].translation,'你好');await c.select(2);await c.select(1);assert.equal(calls,2);await c.select(1,true);assert.equal(calls,3);});
test('快速切歌和停止后过期歌词不会覆盖当前歌曲',async()=>{let finish;const c=new LyricsController({resolve:id=>id===1?new Promise(r=>finish=r):Promise.resolve({lrc:{lyric:'[00:01]新歌'}}),changed:()=>{}});const first=c.select(1);await c.select(2);finish({lrc:{lyric:'[00:01]旧歌'}});await first;assert.equal(c.snapshot().songId,2);assert.equal(c.snapshot().lines[0].text,'新歌');await c.clear();assert.equal(c.snapshot().songId,null);assert.equal(c.cache.size,0);});
test('歌词网络失败不阻断播放，重试可恢复且不暴露请求细节',async()=>{let fail=true;const c=new LyricsController({resolve:async()=>{if(fail)throw new Error('MUSIC_U=secret');return {lrc:{lyric:'[00:00]恢复'}};},changed:()=>{}});await c.select(1);assert.equal(c.snapshot().status,'error');assert.ok(!JSON.stringify(c.snapshot()).includes('secret'));fail=false;await c.select(1,true);assert.equal(c.snapshot().status,'timed');});

test("停止时清除歌词，未完成请求不能重新填入缓存",async()=>{let finish;const c=new LyricsController({resolve:()=>new Promise(r=>finish=r),changed:()=>{}});const task=c.select(1);await c.clear();finish({lrc:{lyric:"[00:00]旧歌词"}});await task;assert.equal(c.snapshot().status,"idle");assert.equal(c.cache.size,0);});
